# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0

name: Docker Build and Push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker images
      run: docker-compose build

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login --username ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin
      if: github.ref == 'refs/heads/master'

    - name: Push image to Aether registry
      run: docker push opennetworking/dbuf:latest
      if: github.ref == 'refs/heads/master'
