name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v .

    - name: Coverage
      run: |
        go test -v -cover -race -coverprofile=coverage.txt -covermode=atomic
        go tool cover -html=coverage.txt -o coverage.html

    - name: Ensure coverage level
      run: |
        target=70
        cov=$(go tool cover -func=coverage.txt | sed -n -E 's/^total.*([[:digit:]][[:digit:]]\.[[:digit:]]+)\%/\1/p')
        if (( $(echo "$cov < $target" | bc -l) )); then echo "Coverage ${cov}% below target of ${target}%"; exit 1; fi;

    - uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.html
